---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sock-shop
  namespace: monitoring
  labels:
    team: plg-stack
spec:
  endpoints:
  - honorLabels: true
    port: "80"
  selector:
    matchLabels:
      operated-prometheus: "true"
